languages:
  Ruby: true
  JavaScript: true
exclude_paths:
- "app/assets/javascripts/dependencies/*"
- "vendor/assets/*"
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
