# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
#

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 9a494c9238095adcabbda8119958bd282a1610b8487f7bdc63953f0254cc14d06a52c31b205b1760d15dea6c10d478dde68b77a0fc2290af39d82b50ec255c7d
  madrid: false
  uweb_api_endpoint: "http://intranet.munimadrid.es:8090/WSUwebv2/services/ServicesUweb?wsdl"
  uweb_api_app_key: "283"
  uweb_api_holders_key: "1487"
  uweb_api_admins_key: "1489"
  uweb_api_users_key: "1488"
  directory_api_endpoint: "http://intranet.munimadrid.es:8090/DirectorioWS/services/Directorio/wsdl/Directorio.wsdl"
  directory_api_app_key: "AGEND"
  uweb_referer_url: "munimadrid.es/uweb/"

staging:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 2a494c9238095adcabbda8119958bd282a1610b8487f7bdc63953f0254cc14d06a52c31b205b1760d15dea6c10d478dde68b77a0fc2290af39d82b50ec255c7d
  madrid: true
  uweb_api_endpoint: "http://desa6intra.munimadrid.es:8090/WSUwebv2/services/ServicesUweb?wsdl"
  uweb_api_app_key: "283"
  uweb_api_holders_key: "1509"
  uweb_api_admins_key: "1543"
  uweb_api_users_key: "1510"
  directory_api_endpoint: "http://intranet.munimadrid.es:8090/DirectorioWS/services/Directorio/wsdl/Directorio.wsdl"
  directory_api_app_key: "AGEND"
  uweb_referer_url: "munimadrid.es/uweb/"

test:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: fa113af080d65ce30bbad72d2d53725260e9d6e650c104719545e0ae8732c826d7eecdd23d295a0a17baf054283d5d8d18b2bdd0ff1eee05c3f18f0d299c966e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  madrid: true
  uweb_api_endpoint: "http://intranet.munimadrid.es:8090/WSUwebv2/services/ServicesUweb?wsdl"
  uweb_api_app_key: "283"
  uweb_api_holders_key: "1487"
  uweb_api_admins_key: "1489"
  uweb_api_users_key: "1488"
  directory_api_endpoint: "http://intranet.munimadrid.es:8090/DirectorioWS/services/Directorio/wsdl/Directorio.wsdl"
  directory_api_app_key: "AGEND"
  uweb_referer_url: "munimadrid.es/uweb/"

preproduction:
  secret_key_base: 2a494c9238095adcabbda8119958bd282a1610b8487f7bdc63953f0254cc14d06a52c31b205b1760d15dea6c10d478dde68b77a0fc2290af39d82b50ec255c7d
  madrid: true
  uweb_api_endpoint: "http://pre6intra.munimadrid.es:8090/WSUwebv2/services/ServicesUweb?wsdl"
  uweb_api_app_key: "261"
  uweb_api_holders_key: "1487"
  uweb_api_admins_key: "1489"
  uweb_api_users_key: "1488"
  directory_api_endpoint: "http://intranet.munimadrid.es:8090/DirectorioWS/services/Directorio/wsdl/Directorio.wsdl"
  directory_api_app_key: "AGEND"
  uweb_referer_url: "munimadrid.es/uweb/"
